[toolchain]
# https://rust-lang.github.io/rustup-components-history/
channel = "nightly-2025-11-20"
components = ["rustfmt", "cargo", "clippy", "rust-analyzer", "llvm-tools", "rust-src"]
profile = "default"
