[global]
show_hash = true
upgrade_only = true
target = ".eget/bin"
all = true

["anza-xyz/agave"]
asset_filters = [".tar.bz2"]
tag = "v3.1.8"

["txtx/surfpool"]
asset_filters = [".tar.gz"]
tag = "v1.0.1"
