[package]
name = "security_00_signer_authorization_secure"
version = "0.0.0"
edition.workspace = true
publish = false

[lib]
crate-type = ["lib"]

[dependencies]
pina = { workspace = true, features = ["logs", "derive"] }

[lints]
workspace = true
