[package]
name = "security_02_owner_checks_secure"
version = "0.0.0"
edition.workspace = true
publish = false

[lib]
crate-type = ["lib"]

[dependencies]
pina = { workspace = true, features = ["logs", "derive", "token"] }

[lints]
workspace = true
